name: Feature Request
description: Request a new or improved a feature in @koliveira15/nx-sonarqube
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request :white_check_mark:
        Please search GitHub for a similar [issue](https://github.com/koliveira15/nx-sonarqube/issues) or [PR](https://github.com/koliveira15/nx-sonarqube/pulls) before submitting a new issue.

  - type: dropdown
    id: type_feature
    attributes:
      label: Which scope/s are relevant/related to the feature request?
      options:
        - "@koliveira15/nx-sonarqube"
        - Astro Docs Site
        - Other
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: Information
      description: Tell us what you want to be added to @koliveira15/nx-sonarqube
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives/workarounds you're currently using

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to provide this feature
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
