name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    with:
      node-version: 20
      main-branch-name: main
      number-of-agents: 3
      parallel-commands-on-agents: |
        npx nx affected -t lint & npx nx affected -t test --configuration=ci & npx nx affected -t build

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    with:
      node-version: 20
      number-of-agents: 3
